### ISSUE TITLE
Concerns About Project Similarity and Lack of Attribution

### ISSUE THREAD

**Issue by Yeetov** [OmegaSunkey/UserPFP-Discord#1]
I would like to address a situation regarding the Discord project, specifically the UserPFP plugin, hosted on the GitHub repository [OmegaSunkey/awesomeplugins](https://github.com/OmegaSunkey/awesomeplugins).

I have noticed a number of similarities between the UserPFP plugin and my own project, USRPFP, developed for the USRPFP (User Profile Picture) Discord server. While I appreciate open-source development and the sharing of ideas, there are concerns regarding the lack of attribution and transparency in this instance.

The UserPFP plugin has been described as a "long-awaited" and "most requested" plugin, offering animated profile pictures without the need for Discord Nitro. However, it is important to note that similar functionality already exists in projects like Vencord (PC/Desktop) and Vendetta (iOS + Android), the latter being my own creation and a feature within the USRPFP server.

My USRPFP server was created on 15/07/2023 and currently boasts 181 real members (excluding Discord "bots").

I have noticed that some members from my USRPFP Discord server have joined the UserPFP Discord server and requested profile pictures, presumably unaware of the inspiration for this project. The USRPFP server has served as a vibrant community for enthusiasts who appreciate the creativity and value of animated profile pictures.

Furthermore, it is worth mentioning that the [Black Box server](https://discord.com/invite/BlackBox) is mentioned as a potential source of inspiration in the UserPFP project's README file. While the Black Box server is indeed relevant to animated content on Discord, it primarily focuses on animated banners rather than profile pictures.

I believe in open communication and collaboration within the open-source community. However, I must express my concern about the lack of attribution and acknowledgement of the source of inspiration for the UserPFP project, specifically the USRPFP server and USRPFP.

I request that the UserPFP project acknowledges its sources of inspiration, including the USRPFP server and [USRPFP Github Page](https://github.com/Yeetov/USRPFP-Reborn), and that this concern is addressed in an amicable and respectful manner. Open-source projects thrive on collaboration, transparency, and mutual respect, and I hope that we can find a resolution that respects these principles.

Please feel free to reach out to me on Discord at FoxStorm1 for more information. Your understanding and willingness to engage in a constructive dialogue are greatly appreciated.

Best regards,

Yeetov (FoxStorm1)

**Comment by aaronateataco2** [comment]
Resolved
